### ISSUE TITLE
[討論] 一些 library 不要放進 webpack

### ISSUE THREAD

**Issue by rwu823** [cepave-f2e/owl-light#8]
現在打包起來太大包我們又沒有自己的 cdn，乾脆用外部的

中國 CDN:
http://www.bootcdn.cn/

**Comment by rwu823** [comment]
![image](https://cloud.githubusercontent.com/assets/890063/21090644/4d989d02-c095-11e6-9b93-391bbf9e37d0.png)

**Comment by rwu823** [comment]
目前用到的都有 `vue`, `echarts`, `axios` and `js-cookie`

**Comment by chuanxd** [comment]
已經這麼大了呀QQ
可用
穩定性應該還行
